gitops-runtime:
  app-proxy:
    env:
      HELM_REPOSITORY: oci://quay.io/codefresh/dev/gitops-runtime
  global:
    codefresh:
      accountId: 6913a63a702b052bb6b2eb29
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - andrii-prom-test-1-runtime.rnd-sandbox.cf-infra.com
        protocol: https
      name: runtime-test-1
      isConfigurationRuntime: true
  installer:
    skipUsageValidation: true
    skipValidation: true
argo-workflows:
  controller:
    workflowDefaults:
      spec:
        artifactRepositoryRef:
          configMap: codefresh-workflows-log-store
          key: codefresh-workflows-log-store
        archiveLogs: true
